#The number Game
print("Find The Number Game")
print()
print()
print("-----------------------------------------")
print("|           |               |           |")
print("|    6      |        9      |      5    |")
print("|           |               |           |")
print("-----------------------------------------")
print("|           |               |           |")
print("|    3      |        7      |      4    |")
print("|           |               |           |")
print("-----------------------------------------")
print("|           |               |           |")
print("|    18     |       63      |      ?    |")
print("|           |               |           |")
print("-----------------------------------------")
print()
print()
print("Find the Value of (?)")
va=int(input("Enter the number :  "))
if va==20:
  print("Correct Answer")
else:
  print("Wrong Answer")
print()
print()
print("-----------------------------------------")
print("|           |               |           |")
print("|     4     |       ?       |      8    |")
print("|           |               |           |")
print("-----------------------------------------")
print("|           |               |           |")
print("|    12     |       35      |     72    |")
print("|           |               |           |")
print("-----------------------------------------")
print("|           |               |           |")
print("|     3     |       6       |      9    |")
print("|           |               |           |")
print("-----------------------------------------")
print()
print()
print("Find the Value of (?)")
val=int(input("Enter the number :  "))
if val==5:
  print("Correct Answer")
else:
  print("Wrong Answer")

